### ISSUE TITLE
Refactor matrix_id to observation_matrix_id

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/matrix_row_coder#18]
@BrianWalters  Over the weekend we figured out that we need to do a somewhat major refactor thanks to a class name collision that I blatantly overlooked (Matrix will become ObservationMatrix), doh. 

* anywhere where we use 'matrix' we'll change it to 'observation_matrix'
* ... potentially other minor refactors here

**Comment by BrianWalters** [comment]
I got this working on my end
